steps:
  - name: Build and Deploy
    run: |
      # Install dependencies
      pip install -r requirements.txt
      # Build the project
      python setup.py build
      # Deploy the project to Cloudflare Pages
      cf-pages deploy
