steps:
  - name: Build and Deploy
    run: |
      # Install dependencies
      pip install requirements.txt
      # Build the project
      python3 app.py
      # Deploy the project to Cloudflare Pages
      cf-pages deploy
