version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 app.py
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    ports:
      - 5000:5000

volumes:
  db_data:

